src/Entity/Soiree.php
<?php

namespace App\Entity;

use App\Repository\SoireeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SoireeRepository::class)
 */
class Soiree
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateStart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateFinish;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateFinish(): ?\DateTimeInterface
    {
        return $this->dateFinish;
    }

    public function setDateFinish(\DateTimeInterface $dateFinish): self
    {
        $this->dateFinish = $dateFinish;

        return $this;
    }
}

src/Entity/Transactions.php
<?php

namespace App\Entity;

use App\Repository\TransactionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransactionsRepository::class)
 */
class Transactions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_membre;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_soiree;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMembre(): ?int
    {
        return $this->id_membre;
    }

    public function setIdMembre(int $id_membre): self
    {
        $this->id_membre = $id_membre;

        return $this;
    }

    public function getIdSoiree(): ?int
    {
        return $this->id_soiree;
    }

    public function setIdSoiree(int $id_soiree): self
    {
        $this->id_soiree = $id_soiree;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }
}

src/Controller/SoireesController.php
<?php

namespace App\Controller;

use App\Entity\Membres;
use App\Entity\Soiree;
use App\Entity\Transactions;
use App\Form\AddSoireeType;
use App\Repository\TransactionsRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SoireesController extends AbstractController
{
    /**
     * @Route("/soirees", name="soirees")
     */
    public function index(): Response
    {
        return $this->render('soirees/index.html.twig', [
            'controller_name' => 'SoireesController',
        ]);
    }


    #[Route('/soirees/add', name:'soirees_add')]
    public function soirees_add(Request $request)
    {
        $soirees = new Soiree;

        $form = $this->createForm(AddSoireeType::class, $soirees);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();

            $em->persist($soirees);

            $em->flush();

            return $this->redirectToRoute("home");
        }


        return $this->render('soirees/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/soirees/list', name:'soirees_list')]
    public function soirees_list(Request $request, ManagerRegistry $doctrine)
    {
        $soirees = $doctrine->getRepository(Soiree::class)->findAll();


        return $this->render('soirees/list.html.twig', [
            'soirees' => $soirees,
        ]);
    }

    #[Route('soirees/manage/{id}', name:'soirees_manage')]
    public function soirees_manage($id, Request $request, ManagerRegistry $doctrine, TransactionsRepository $tr){

        $membres = $doctrine->getRepository(Membres::class)->findBy(['id_soiree' => $id]);

        $party = $doctrine->getRepository(Membres::class)->find($id);

        $transactions = $doctrine->getRepository(Transactions::class)->findBy(['id_soiree' => $id]);
        /*$em = $this->getDoctrine()->getManager();

        $query = $em->createQuery('SELECT transactions.id,transactions.montant,membres.name FROM transactions JOIN membres ON membres.id = transactions.id_membre WHERE transactions.id = :id');
        $query->setParameter(':id', $id);
        $transactions = $query->getResult();
*/

        $totalTransactions = $this->getDoctrine()
            ->getRepository(Transactions::class)
            ->getTotalTransactions($id);


        return $this->render('soirees/manage.html.twig', [
            'membres' => $membres,
            'party' => $party,
            'transactions' => $transactions,
            'totalTransactions' => $totalTransactions
        ]);

    }

    #[Route('soirees/manage-post', name:'soirees_manage_post')]
    public function soirees_manage_post(Request $request){

        $em = $this->getDoctrine()->getManager();
        $transaction = new Transactions;

        //post input (soirees/manage.html.twig)
        $transaction->setIdMembre(filter_input(INPUT_POST, 'idM'));
        $transaction->setIdSoiree(filter_input(INPUT_POST, 'idP'));
        $transaction->setMontant(filter_input(INPUT_POST, 'montant'));

        $em->persist($transaction);

        $em->flush();

        return $this->redirectToRoute("soirees_list");
    }

    #[Route('soirees/delete/{id}', name:'soirees_delete')]
    public function soiree_delete($id,ManagerRegistry $doctrine){

        $em = $doctrine->getManager();
        $soiree = $em->getRepository(Soiree::class)->find($id);

        $em->remove($soiree);
        $em->flush();

        return $this->redirectToRoute("soirees_list");

    }
}

templates/soirees/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une soirée{% endblock %}

{% block body %}

    <h1>Ajouter une soirée</h1>

    {{ form(form) }}
{% endblock %}

templates/soirees/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SoireesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'W:/wamp64/www/symfoTricount/src/Controller/SoireesController.php'|file_link(0) }}">src/Controller/SoireesController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'W:/wamp64/www/symfoTricount/templates/soirees/index.html.twig'|file_link(0) }}">templates/soirees/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/soirees/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}List des soirées{% endblock %}

{% block body %}
    <div class="container">

        <h1>Liste des soirées </h1>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nom</th>
                <th scope="col">Date du début</th>
                <th scope="col">Date de fin</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>

            <tbody>
            {% for s in soirees %}
                <tr>
                    <td>{{ s.id }}</td>
                    <td>{{ s.name }}</td>
                    <td>{{ s.dateStart|date('d-m-Y') }}</td>
                    <td>{{ s.dateFinish|date('d-m-Y') }}</td>
                    <td>
                        <a href="{{ path('soirees_manage', {"id":s.id}) }}" class="btn btn-sm btn-success">Gérer</a>
                        <a href="#" class="btn btn-sm btn-warning">Modifier</a>
                        <a href="{{ path('soirees_delete', {"id":s.id}) }}" class="btn btn-sm btn-danger">Supprimer</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

templates/soirees/manage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion de là soirée {{ party.name }}{% endblock %}

{% block body %}
    <div class="container">
        {% if membres|length != 0 %}

        <h1>Cagnotte totale: <strong>{{ totalTransactions.montant }}</strong></h1>
        <hr class="my-4">

        {% for m in membres %}
                <form method="post" action="{{ path('soirees_manage_post') }}">
                    <div class="input-group mb-3">
                        <input type="hidden" name="idM" value="{{ m.id }}" hidden>
                        <input type="hidden" name="idP" value="{{ party.id }}" hidden>
                        <label class="input-group-text" for="membre-{{ m.name }}">Compte de {{ m.name }}</label>
                        <input class="form-control" type="number" id="membre-{{ m.name }}" name="montant">

                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Sauvegarder</button>
                    </div>
                </form>
            {% endfor %}

            <h1>Historique des transactions pour cette sorée</h1>
            <hr class="my-4">

            <!-- Historique des transactions -->
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Montant</th>
                </tr>
                </thead>

                <tbody>
                {% for t in transactions %}
                    <tr>
                        <td>{{ t.id }}</td>
                        <td>{{ t.idMembre }}</td>
                        <td>{{ t.montant }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>


            <h1>Répartition des paiements</h1>
            <hr class="my-4">

            <!-- Répartition des paiements -->
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Montant dû au pot commun</th>
                </tr>
                </thead>

                <tbody>

                {% for t in transactions %}
                    <tr>
                        <td>{{ t.id }}</td>
                        <td>{{ t.idMembre }}</td>
                        <td>{{ (totalTransactions.montant - t.montant)/(transactions| length - 1) - t.montant }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>


            <!-- Si on à 0 membres dans là soirée... -->
        {% else %}

            <div class="text-center">
                <span>Aucuns membres présents à cette soirée...</span>

                <p>Vous pouvez en ajouter <a href="{{ path('soirees_add') }}">ici</a> </p>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}